import os
import re
import requests
from datetime import datetime
from bs4 import BeautifulSoup
from urllib.parse import urljoin
from langchain_community.utilities import ApifyWrapper
from langchain.output_parsers import PydanticOutputParser
from langchain_core.pydantic_v1 import BaseModel, Field
from langchain.prompts import PromptTemplate
from langchain.schema import Document
from langchain_openai import ChatOpenAI
from notion_client import Client
from youtube_transcript_api import YouTubeTranscriptApi
from urllib.parse import urlparse, parse_qs
from logger import setup_logger

from dotenv import load_dotenv

from prompt_templates import report_prompt_template

load_dotenv()

logger = setup_logger()


class Report(BaseModel):
    title: str = Field(description="A clear and concise title of the report")
    content: str = Field(
        description="The content of the report. Do not add the main title here, instead use the appropriate field."
    )


class ApifyInterface:
    website_run_input = {
        "crawlerType": "playwright:firefox",
        "requestTimeoutSecs": 60,
        "initialConcurrency": 3,
        "maxConcurrency": 10,
        "maxCrawlDepth": 1,
        "maxCrawlPages": 1,
        "proxyConfiguration": {
            "useApifyProxy": True,
            "apifyProxyGroups": ["RESIDENTIAL"],
        },
        "dynamicContentWaitSecs": 5,
    }

    youtube_run_input = {
        "downloadSubtitles": True,
        "hasSubtitles": True,
        "maxResults": 1,
        "preferAutoGeneratedSubtitles": False,
        "subtitlesFormat": "plaintext",
    }

    def __init__(self):
        self.client = ApifyWrapper()

    def scrape_website(self, url: str) -> Document:
        def mapping_function(item: dict) -> Document:
            return Document(
                page_content=item.get("markdown", "") or item.get("text", ""),
                metadata={"icon": self.__get_website_favicon(url)},
            )

        logger.info(f"Scraping website: {url}")

        trials = [
            {"saveHtmlAsFile": True, "saveMarkdown": False},
            {"saveHtmlAsFile": False, "saveMarkdown": True},
        ]

        while trials:
            try:
                loader = self.client.call_actor(
                    actor_id="apify/website-content-crawler",
                    run_input={
                        **self.website_run_input,
                        "startUrls": [{"url": url}],
                        **trials.pop(0),
                    },
                    timeout_secs=180,
                    memory_mbytes=4096,
                    dataset_mapping_function=mapping_function,
                )
                return loader.load()[0]
            except Exception as e:
                logger.error(f"Failed to scrape website. Reason: {e}")

                if not trials:
                    raise e

    def scrape_youtube(self, url: str) -> Document:
        def mapping_function(item: dict) -> Document:
            if not item.get("subtitles"):
                raise ValueError("No subtitles found")
            
            page_content = self.__create_youtube_content(item)
            
            return Document(
                page_content=page_content,
                metadata={
                    "icon": self.__get_youtube_favicon(url),
                    "cover": item.get("thumbnailUrl"),
                },
            )

        logger.info(f"Scraping YouTube video: {url}")

        languages = ["en", "it", "nl"]

        while languages:
            try:
                loader = self.client.call_actor(
                    actor_id="streamers/youtube-scraper",
                    run_input={
                        **self.youtube_run_input,
                        "startUrls": [{"url": url, "method": "GET"}],
                        "subtitlesLanguage": languages.pop(0),
                    },
                    timeout_secs=60,
                    memory_mbytes=1024,
                    dataset_mapping_function=mapping_function,
                )
                content = loader.load()[0]
                if content:
                    return content
            except Exception as e:
                logger.error(f"Failed to scrape YouTube video with Apify. Reason: {e}")

                if not languages:
                    raise e

    def __get_website_favicon(self, url: str) -> str:
        response = requests.get(url)
        try:
            response.raise_for_status()
        except requests.exceptions.HTTPError as e:
            logger.error(f"Failed to fetch favicon. Reason: {e}")
            return None

        soup = BeautifulSoup(response.text, "html.parser")
        icon_link = None

        for rel in ["icon", "shortcut icon"]:
            icon_link = soup.find("link", rel=rel)
            if icon_link:
                break

        if icon_link and "href" in icon_link.attrs:
            favicon_url = urljoin(url, icon_link["href"])
            logger.info(f"Found favicon: {favicon_url}")
            return favicon_url

        logger.warning("No favicon found")
        return None

    def __get_youtube_favicon(self, url: str) -> str:
        logger.info(f"Using default favicon for YouTube URL: {url}")
        return "https://img.icons8.com/?size=100&id=19318&format=png&color=000000"

    def __create_youtube_content(self, item: dict) -> str:
        """Create combined content with metadata and subtitles"""
        content_parts = []
        
        # Add video metadata
        metadata_parts = []
        if item.get("title"):
            metadata_parts.append(f"**Video Title:** {item['title']}")
        if item.get("channelName"):
            metadata_parts.append(f"**Channel:** {item['channelName']}")
        if item.get("channelUrl"):
            metadata_parts.append(f"**Channel URL:** {item['channelUrl']}")
        if item.get("viewCount"):
            metadata_parts.append(f"**Views:** {item['viewCount']:,}")
        if item.get("likes"):
            metadata_parts.append(f"**Likes:** {item['likes']:,}")
        if item.get("duration"):
            metadata_parts.append(f"**Duration:** {item['duration']}")
        if item.get("date"):
            metadata_parts.append(f"**Published:** {item['date']}")
        
        if metadata_parts:
            content_parts.append("\n".join(metadata_parts))
            content_parts.append("")  # Add spacing
        
        # Add subtitle content
        subtitles = item["subtitles"]
        if isinstance(subtitles, list):
            texts = [sub["plaintext"] for sub in subtitles if isinstance(sub, dict) and "plaintext" in sub]
            content_parts.append(" ".join(texts))
        else:
            content_parts.append(str(subtitles))
        
        return "\n".join(content_parts)


class YoutubeInterface:
    def __extract_video_id(self, url: str) -> str:
        parsed_url = urlparse(url)
        if parsed_url.hostname == "youtu.be":
            return parsed_url.path[1:]
        if parsed_url.hostname in ("www.youtube.com", "youtube.com"):
            if parsed_url.path == "/watch":
                return parse_qs(parsed_url.query)["v"][0]
            if parsed_url.path.startswith(("/embed/", "/v/")):
                return parsed_url.path.split("/")[2]
        return None

    def __format_transcript(self, transcript: list) -> str:
        return " ".join([entry["text"] for entry in transcript])

    def scrape_video(self, url: str) -> Document:
        video_id = self.__extract_video_id(url)
        if not video_id:
            raise ValueError("Invalid YouTube URL")

        transcript = (
            YouTubeTranscriptApi.list_transcripts(video_id)
            .find_transcript(["en", "it", "nl"])
            .fetch()
        )
        return Document(
            page_content=self.__format_transcript(transcript),
            metadata={
                "icon": self.__get_favicon(url),
                "cover": self.__get_thumbnail(url),
            },
        )

    def __get_favicon(self, url: str) -> str:
        logger.info(f"Using default favicon for YouTube URL: {url}")
        return "https://img.icons8.com/?size=100&id=19318&format=png&color=000000"

    def __get_thumbnail(self, url: str) -> str:
        video_id = self.__extract_video_id(url)
        if not video_id:
            raise ValueError("Invalid YouTube URL")

        thumbnail_url = f"https://img.youtube.com/vi/{video_id}/maxresdefault.jpg"

        response = requests.head(thumbnail_url)
        if response.status_code != 200:
            thumbnail_url = f"https://img.youtube.com/vi/{video_id}/hqdefault.jpg"

        logger.info(f"Using thumbnail: {thumbnail_url}")
        return thumbnail_url

    def standardize_url(self, url: str) -> str:
        video_id = self.__extract_video_id(url)
        if not video_id:
            raise ValueError("Invalid YouTube URL")
        return f"https://www.youtube.com/watch?v={video_id}"


class NotionInterface:
    # Regex patterns
    h_re_pattern = r"^#+ "
    numbered_list_re_pattern = r"^\d+\. "
    bulleted_list_re_pattern = r"^[-*] "
    bold_re_pattern = r"\*\*[^*]+\*\*"
    italic_re_pattern = r"\*[^*]+\*"
    link_re_pattern = r"\[.*?\)"
    divider_re_pattern = r"^-{3,}$|^\*{3,}$|^_{3,}$"

    # Markdown patterns
    h1_pattern = "# "
    h2_pattern = "## "
    h3_pattern = "###"  # NOTE: No trailing space to label h4, h5, and so on as h3.

    REPORT_PROMPT = PromptTemplate.from_template(template=report_prompt_template)

    def __init__(self, is_youtube: bool):
        self.client = Client(auth=os.environ["NOTION_TOKEN"])
        self.database_id = (
            os.environ["NOTION_VIDEOS_DATABASE_ID"]
            if is_youtube
            else os.environ["NOTION_WEBSITES_DATABASE_ID"]
        )

    def __identify_block_type(self, text: str) -> str:
        # Check for dividers first (---, ***, ___)
        if re.match(self.divider_re_pattern, text):
            return "divider"
        if text.startswith(self.h3_pattern):
            return "heading_3"
        if text.startswith(self.h2_pattern):
            return "heading_2"
        if text.startswith(self.h1_pattern):
            return "heading_1"
        if re.match(self.numbered_list_re_pattern, text):
            return "numbered_list_item"
        if re.match(self.bulleted_list_re_pattern, text):
            return "bulleted_list_item"
        return "paragraph"

    def __create_block(self, text: str, block_type: str) -> dict:
        if block_type == "divider":
            return {
                "object": "block",
                "type": "divider",
                "divider": {}
            }
        if block_type.startswith("heading"):
            text = re.sub(self.h_re_pattern, "", text)
        if block_type == "numbered_list_item":
            text = re.sub(self.numbered_list_re_pattern, "", text)
        if block_type == "bulleted_list_item":
            text = re.sub(self.bulleted_list_re_pattern, "", text)

        # Split text into bold, italic, and links
        combined_pattern = (
            f"({self.bold_re_pattern}|{self.italic_re_pattern}|{self.link_re_pattern})"
        )
        split_text = [part for part in re.split(combined_pattern, text) if part]

        # Create rich text
        rich_text = []
        for part in split_text:
            if not part:
                continue

            logger.info(f"Assigning rich text to block: {block_type}")
            if part.startswith("**"):
                rich_text.append(
                    {
                        "type": "text",
                        "text": {"content": part.replace("**", "")},
                        "annotations": {"bold": True},
                    }
                )
            elif part.startswith("*"):
                rich_text.append(
                    {
                        "type": "text",
                        "text": {"content": part.replace("*", "")},
                        "annotations": {"italic": True},
                    }
                )
            elif part.startswith("[") and part.endswith(")"):
                print(part)
                link_text, link_url = part[1:-1].split("](")
                rich_text.append(
                    {
                        "type": "text",
                        "text": {"content": link_text, "link": {"url": link_url}},
                    }
                )
            else:
                rich_text.append({"type": "text", "text": {"content": part}})

        return {
            "object": "block",
            "type": block_type,
            block_type: {"rich_text": rich_text},
        }

    def __get_indentation_level(self, line: str) -> int:
        """Get the indentation level of a line (number of leading spaces/tabs)"""
        indent = len(line) - len(line.lstrip())
        # Normalize: 2 or 4 spaces = 1 level, 1 tab = 1 level
        if '\t' in line[:indent]:
            return line[:indent].count('\t')
        # Assume 2 or 4 spaces per indentation level
        spaces = indent
        if spaces >= 4:
            return spaces // 4
        elif spaces >= 2:
            return spaces // 2
        return 0
    
    def __parse_nested_blocks(self, content: str) -> list:
        """Parse content into blocks with nested list support"""
        lines = content.split("\n")
        blocks = []
        i = 0
        
        while i < len(lines):
            line = lines[i]
            stripped_line = line.strip()
            
            # Skip empty lines
            if not stripped_line:
                i += 1
                continue
            
            indent_level = self.__get_indentation_level(line)
            block_type = self.__identify_block_type(stripped_line)
            
            # If it's a list item, check for nested children
            if block_type in ["bulleted_list_item", "numbered_list_item"]:
                block = self.__create_block(stripped_line, block_type)
                
                # Look ahead for nested items
                children = []
                j = i + 1
                while j < len(lines):
                    next_line = lines[j]
                    next_stripped = next_line.strip()
                    
                    if not next_stripped:
                        j += 1
                        continue
                    
                    next_indent = self.__get_indentation_level(next_line)
                    next_type = self.__identify_block_type(next_stripped)
                    
                    # If it's more indented and is a list item, it's a child
                    if next_indent > indent_level and next_type in ["bulleted_list_item", "numbered_list_item"]:
                        # Recursively parse nested items
                        # For now, we'll handle one level of nesting
                        child_block = self.__create_block(next_stripped, next_type)
                        children.append(child_block)
                        j += 1
                    elif next_indent <= indent_level:
                        # Back to same or lower indentation level
                        break
                    else:
                        # Different block type at higher indentation
                        j += 1
                
                # Add children if any were found
                if children:
                    block[block_type]["children"] = children
                    i = j  # Skip the lines we've already processed
                else:
                    i += 1
                
                blocks.append(block)
            else:
                # Non-list items
                blocks.append(self.__create_block(stripped_line, block_type))
                i += 1
        
        return blocks

    def get_database_entry(self, url: str) -> dict | None:        
        # Create filter for the URL property
        filter_params = {
            "filter": {
                "property": "URL",
                "url": {
                    "equals": url
                }
            },
            "sorts": [
                {
                    "timestamp": "last_edited_time",
                    "direction": "descending"
                }
            ]
        }
        
        response = self.client.databases.query(
            database_id=self.database_id,
            **filter_params
        )
        
        # Only process the first (most recent) result if any exist
        if response["results"]:
            page = response["results"][0]
            title = page["properties"]["Name"]["title"][0]["text"]["content"] if page["properties"]["Name"]["title"] else "Untitled"
            page_url = page["url"]
            
            return {
                "id": page["id"],
                "title": title,
                "url": url,
                "page_url": page_url,
                "created_time": page["created_time"],
                "last_edited_time": page["last_edited_time"]
            }
        
    def generate_report(self, content: str, guidance: str = "") -> Report:
        logger.info(f"Generating report with guidance: {guidance}")

        # Create report chain
        llm = ChatOpenAI(model="gpt-4.1-mini", temperature=0)
        parser = PydanticOutputParser(pydantic_object=Report)
        chain = self.REPORT_PROMPT | llm | parser
        prompt_context = {
            "content": content,
            "guidance": guidance,
            "format_instructions": parser.get_format_instructions(),
            "current_date_time": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        }
        result = chain.invoke(prompt_context)
        return result

    def create_page(
        self,
        url: str,
        report: Report,
        icon: str | None = None,
        cover: str | None = None,
    ) -> dict:
        # Parse content into blocks with nested list support
        children_blocks = self.__parse_nested_blocks(report.content)

        # Create new page
        kwargs = {
            "parent": {"database_id": self.database_id},
            "properties": {
                "Name": {"title": [{"text": {"content": report.title}}]},
                "URL": {"url": url},
            },
            "children": children_blocks,
        }

        if icon:
            kwargs["icon"] = {"type": "external", "external": {"url": icon}}

        if cover:
            kwargs["cover"] = {"type": "external", "external": {"url": cover}}

        page = self.client.pages.create(**kwargs)

        logger.info(f"Created new page: {page['url']}")
        return {
            "id": page["id"], 
            "title": report.title,
            "url": url,
            "page_url": page["url"],
            "created_time": page["created_time"],
            "last_edited_time": page["last_edited_time"]
        }

def is_youtube_url(url: str) -> bool:
    return urlparse(url).netloc in ["www.youtube.com", "youtu.be"]

def scrape_website_with_apify(url: str) -> dict:
    apify = ApifyInterface()
    document = apify.scrape_website(url)
    return {
        "content": document.page_content,
        "icon": document.metadata.get("icon"),
        "cover": document.metadata.get("cover"),
    }


def scrape_youtube_with_apify(url: str) -> dict:
    apify = ApifyInterface()
    document = apify.scrape_youtube(url)
    return {
        "content": document.page_content,
        "icon": document.metadata.get("icon"),
        "cover": document.metadata.get("cover"),
    }


def scrape_youtube_with_transcript(url: str) -> dict:
    youtube = YoutubeInterface()
    document = youtube.scrape_video(url)
    return {
        "content": document.page_content,
        "icon": document.metadata.get("icon"),
        "cover": document.metadata.get("cover"),
    }
